project:
  type: website

website:
  title: "Juan C. Arboleda R."
  favicon: imgs/nea-onnim.svg
  back-to-top-navigation: true

  navbar:
    background: '#202025'
    foreground: '#dcdcff'

    left:
      - icon: person
        href: index.md
        text: About
      - icon: journal-code
        href: research.md
      - icon: journal-text
        href: teaching.md
      - icon: pencil-square
        href: posts.md

    tools:
      - icon: envelope-fill
        href: mailto:juan.arboleda2@udea.edu.co
      - icon: mastodon
        href: https://biologists.social/@Nesper94
      - icon: github
        href: https://github.com/Nesper94
      - icon: twitter
        href: https://twitter.com/Nesper94
    
    logo: imgs/nea-onnim.svg

  comments:
    utterances:
      repo: Nesper94/Nesper94.github.io

format:
  html:
    theme:
      light: [flatly, font.scss]
      dark: [cyborg, font.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true

